project:
  type: website
  output-dir: docs
  
website:
  title: "C. Andrew Basham"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: osf
        href: https://osf.io/mny8b/
      - icon: github
        href: https://github.com/CAndrewBasham/web
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, C. Andrew Basham"

format:
  html:
    theme: cerulean
    toc: true

editor: source

