project:
  type: website
  output-dir: docs

website:
  title: "C. Andrew Basham"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: software/index.qmd
        text: Software
      - href: projects/index.qmd
        text: Projects
      - href: portfolio/index.qmd
      - href: Education/index.qmd
      - href: cv1.qmd
        text: CV
      
    tools:      
      - icon: website
        href: https://andrewbasham.com/
      - icon: github
        href: https://github.com/CAndrewBasham/web
      - icon: linkedin
        href: https://www.linkedin.com/in/candrewbasham/
      - icon: osf
        href: https://osf.io/mny8b/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, C. Andrew Basham"
format:
  html:
    theme: vapor
    toc: true

editor: source


