project:
  type: website
  output-dir: docs

website:
  title: "C. Andrew Basham"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
      - text: Projects
      - href: portfolio/index.qmd
      - text: Portfolio
      
    tools:      
      - icon: twitter
        href: https://twitter.com/CAndrewBasham/
      - icon: github
        href: https://github.com/CAndrewBasham/web
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, C. Andrew Basham"
format:
  html:
    theme: vapor
    toc: true

editor: source


