---
title: "CV"
editor: visual
---

::: {#hms_cv_title}
**The** **Faculty of Medicine of Harvard University** **Curriculum Vitae**
:::

## Contact Information

+-----------------------------+--------------------------------------------------------+
| **Date Prepared:**          | November $8^{th}$, 2024                                |
+-----------------------------+--------------------------------------------------------+
| **Name:**                   | Christopher [Andrew]{.underline} Basham                |
+-----------------------------+--------------------------------------------------------+
| **Office:**                 | 1620 Tremont Street - Unit 3030                        |
|                             |                                                        |
|                             | Boston, MA 02120                                       |
+-----------------------------+--------------------------------------------------------+
| **Email:**                  | cv\@andrewbasham.com                                   |
+-----------------------------+--------------------------------------------------------+
| **Website:**                | <https://andrewbasham.com/>                            |
+-----------------------------+--------------------------------------------------------+
| **LinkedIn:**               | <https://www.linkedin.com/in/candrewbasham/>           |
+-----------------------------+--------------------------------------------------------+
| **ORCiD:**                  | <https://orcid.org/0000-0003-0506-7936>                |
+-----------------------------+--------------------------------------------------------+
| **GitHub Profile:**         | <https://github.com/CAndrewBasham>                     |
+-----------------------------+--------------------------------------------------------+
| **GitHub Pages:**           | <https://candrewbasham.github.io/web/>                 |
+-----------------------------+--------------------------------------------------------+
| **ResearchGate:**           | <https://www.researchgate.net/profile/C-Andrew-Basham> |
+-----------------------------+--------------------------------------------------------+
| **Google Scholar:**         | <https://tinyurl.com/3wz4sken>                         |
+-----------------------------+--------------------------------------------------------+
| **Open Science Framework:** | <https://osf.io/mny8b/>                                |
+-----------------------------+--------------------------------------------------------+

## Education:

+:----------------+:-------------+:-----------------------------+:-------------------------------+
| 09/2017-10/2021 | PhD          | Population and Public Health | University of British Columbia |
+-----------------+--------------+------------------------------+--------------------------------+
| 09/2010-02/2016 | MSc          | Community Health Sciences    | University of Manitoba         |
+-----------------+--------------+------------------------------+--------------------------------+
| 09/2004-05/2008 | BA           | Environmental/Urban Studies  | University of Winnipeg         |
+-----------------+--------------+------------------------------+--------------------------------+

## Postdoctoral Training:

+-----------------+-----------------+:-------------------------------------------------------+:-----------------------+
| 03/2022-06/2024 | Research Fellow | Division of Pharmacoepidemiology and Pharmacoeconomics | Harvard Medical School |
+-----------------+-----------------+--------------------------------------------------------+------------------------+

## Appointments at Hospitals/Affiliated Institutions:

+------------------+-----------------+--------------------------------------------------------+:-----------------------------+
| 03/2022– 06/2024 | Research Fellow | Division of Pharmacoepidemiology and Pharmacoeconomics | Brigham and Women's Hospital |
+------------------+-----------------+--------------------------------------------------------+------------------------------+

**Other Professional Positions:**

+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Year(s)** | **Position**\| **Department**\| **Institution**\|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2008-2010   | Health Policy Analyst \| Health Department \| Manitoba Keewatinowi Okimakanak \| ------------------------------+---------------------------------------------------+---------------------------------------------\|2012\| Research Assistant\| Department of Emergency Medicine\| University of Manitoba\| Statistical Analyst \| First Nations Regional Longitudinal Health Survey \| Assembly of Manitoba Chiefs \| ------------------------------+---------------------------------------------------+---------------------------------------------\| 2013 \| Program Specialist \| Aboriginal Health Programs \| Winnipeg Regional Health Authority \| \| \| \| |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 4-2015 \| Research Assistant \| Centre for Aboriginal Health Research \| University of Manitoba \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 5 \| Research Consultant \| Health Department \| Manitoba Keewatinowi Okimakanak \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 5-2017 \| Data Analyst \| Manitoba Centre for Health Policy \| University of Manitoba \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 7-2021 \| Graduate Research Assistant \| Tuberculosis Program \| British Columbia Centre for Disease Control \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 8 \| Teaching Assistant \| School of Population and Public Health \| University of British Columbia \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 9 \| Graduate Research Assistant \| Department of Pathology and Laboratory Medicine \| University of British Columbia \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 0-2021 \| Graduate Research Assistant \| Canadian Disability Participation Project \| University of British Columbia \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 1-2022 \| Evidence Reviewer \| McGill International TB Centre \| McGill University \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             | 2- \| Statistical Consultant \| Faculty of Health Sciences \| Simon Fraser University \| \| \| \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
