---
title: "Projects"
bibliography: references.bib
---

## Survivorship Epidemiology:

The goal of this program of methodological research is to advance theory, concepts, models, and tools for descriptive, predictive, and inferences about critical illness survivor health outcomes, their pathology and diagnosis, biomedical treatment, the physiological and psychological changes associated with these processes, and their sociocultural contexts, including financial and economic burdens, healthcare services, and advances in pharmaceutical treatment , aprocesses, services relevant to them.

I am creating an international network of epidemiologists studying critical illness survivorship. The object of this network is the establishment of an academic society dedicated to advancing dialogue, theory, methods, and applications to improve the rigor, representativeness, relevance, and reproducibility of the epidemiological study of critical illness survivorship.

#### Specific Aims

1.  Distilling epidemiological principles common to survivorship and forming them into coherent quantitative theory,

2.  Developing epidemiological methods to analyze survivor health outcomes selecting relevant com- parator groups, and coupling them with estimators that can reasonably be assumed to estimate quantities of interest in survivorship research;

3.  Define the limits of generalizability for estimands and estimators within and across fields of medicine, patient populations, and geographies.

### Publications

1.  Basham CA, Romanowski K, Johnston JC. Life after tuberculosis: planning for health. Lancet Respiratory Medicine. 2019;7(12):1004–1006.

2.  Basham CA. Post–tuberculosis outcomes science: a sub–discipline for TB survivorship research? International Journal of Tuberculosis and Lung Disease. 2021; 25(6):498-501.

3.  Basham CA, Smith S, Romanowski K, Johnston JC. Cardiovascular morbidity and mortality among people diagnosed with tuberculosis: a systematic review and meta-analysis. PLoS ONE 15(7):e0235821.

4.  Basham CA, Cook, VJ, Johnston JC. Towards a ‘fourth 90’: A population–based analysis of post–tuberculosis pulmonary function testing in British Columbia, Canada, 1985–2015. European Respiratory Journal. April 2020:2000384.

5.  Basham CA, Karim ME, Cook VJ, Patrick DM, Johnston JC. Post–tuberculosis mortality risk among immigrants to British Columbia, Canada, 1985–2015: a time–dependent Cox regression analysis of linked immigration, public health, and vital statistics data. Can J Public Heal. 2021;112(1):132–141.

6.  Basham CA, Karim ME, Cook, VJ, Patrick DM, Johnston JC. Post–tuberculosis airway disease among people immigrating to British Columbia, Canada, 1985–2015: a population–based cohort study. EClinicalMedicine. 2021;33:100752.

7.  Basham CA, Karim ME, Cook, VJ, Patrick DM, Johnston JC. Tuberculosis–associated depression risk: a population–based cohort study of people immigrating to British Columbia, Canada, 1985–2015. Annals of Epidemiology. 2021; 63: 7-14.

8.  Basham CA, Karim ME. An E–value analysis of potential unmeasured or residual confounding in systematic reviews of post–TB mortality, respiratory disease, and cardiovascular disease. Annals of Epidemiology. 2022; 68: 24-31.

9.  Basham CA, Karim ME, Johnston JC. Multimorbidity prevalence and chronic disease patterns among tuberculosis survivors in a high-income setting. Can J Public Heal. 2023 Apr;114(2):264-276.

## Foundations for Pharmacoequity:

Data provenance, lineage, and epidemiological analysis methods for health equity, focusing on race and ethnicity data use in pharmacoepidemiology. I created this program of research to increase the rigor, transparency, and reproducibility of race and ethnicity data collection, analysis, and reporting. Without valid, complete, and reliable race and ethnicity data, health equity initiatives are hampered in terms of identifying population trends in health outcomes, including disparities between people identifying in different groups. Missing race and ethnicity data often leads to differential exclusion from observational research when complete case analyses are employed.

### REVIEW-RWD (Race and ethnicity variables investigation for epidemiology weaknessed in real-world)

I conceptualized and obtained funding for a structural missing data investigation of race and ethnicity variables within a novel linkage of MGB’s Research Patient Data Registry (EHR) data and the Centers for Medicaid and Medicare Services (claims) data I designed the database linkage to preserve as many row values for any and all race and ethnicity variables in these three databases spanning 2015-2019.

### RECORD-Race and Ethnicity

A key research question I am pursuing within the Foundations for Pharmacoequity program is: ”How do race and ethnicity influence real-world data (RWD) and what effect do these influences have on the reproducibility of real-world evidence (RWE), generally, and pharmacoepidemiology, specifically?” Towards answering this question I reviewed the literature and considered, theoretically, the influence of race and ethnicity, and the phenomena for which they are used as proxy measures or otherwise may represent, within pharmacoepidemiological research and how that may affect the reproducibility of methods, results, and inferences of RWE. As an initial contribution I have a manuscript in requested revision stage that at Pharmacoepidemiology and Drug Safety calling for improved reporting of race and ethnicity variable-related decisions by authors and interpretations that consider race and ethnicity variables’ roles and impacts on RWE. This manuscript included a draft checklist, RECORD-Race and Ethnicity, was included in this manuscript, building on The REporting of studies Conducted using Observational Routinely-collected health Data (RECORD) statement. RECORD-RE incorporates evidence of poor reporting of race and ethnicity variables and their handling in epidemiological research articles drawing on recent systematic reviews and expert recommendations and reproducibility guidance.

## Causing careers: causal inference approaches to epidemiological education

In this program of research, I am developing novel epidemiological approaches to education and career planning.

### Self-DAG:

causal pathways from educational exposures to career outcomes Travelling backwards through time to identify the causal mechanisms in generating desired educational and career outcomes - the long-term trainee goals - to the current time, we will ”backcast” from the outcome to the preconditions for that outcome, and then ascertain the exposure(s) necessary, and sufficient, to cause the all the intermediate educational and career outcomes they are aiming for.

### Epidemiological concept mapping:

Modelling epidemiological knowledge and learning Engaging learners in mapping their understanding of epidemiology, the connections between concepts such as the concept of a study population, and how descriptive and causal inferences are drawn from analytic samples to those study populations, and how such inferences could be biased. The screen recording feature of Cmap software will allow tracking the development of learners’ epidemiological knowledge model (<https://cmap.ihmc.us/docs/learn.php).> Transparent evaluation of knowledge maps, including instructional team maps, pre/post-course will demonstrate varying shapes and levels of conceptual understanding, guiding development of lessons building on those conceptualizations. This is an unexplored potentially scalable innovation for epidemiological education and knowledge modelling. I provide an example of one I created