---
title: "Curriculum Vitae"
author: "C. Andrew Basham, BA, MSc, PhD"
date: "September 27, 2024"
---
<<<<<<< HEAD
=======
**The Faculty of Medicine of Harvard University**
**Curriculum Vitae**

Date Prepared:	October 4, 2024
Name:	Christopher Andrew Basham
Office:	1620 Tremont Street, Unit 3030, Boston, MA 02120
Email:	cv@andrewbasham.com  
Website:	https://andrewbasham.com/
LinkedIn:	https://www.linkedin.com/in/candrewbasham/
ORCiD:	https://orcid.org/0000-0003-0506-7936
Open Science Framework:	https://osf.io/mny8b/
GitHub Profile:	https://github.com/CAndrewBasham
GitHub Webpage: 	https://candrewbasham.github.io/web/ 
ResearchGate:	https://www.researchgate.net/profile/C-Andrew-Basham
Google Scholar:	https://tinyurl.com/3wz4sken


Education:	
09/2017-10/2021	PhD	Population and Public Health	University of British Columbia
09/2010-02/2016	MSc	Community Health Sciences	University of Manitoba
09/2004-05/2008	BA	Environmental/Urban Studies	University of Winnipeg


Postdoctoral Training:
03/2022-06/2024	Research Fellow	Division of Pharmacoepidemiology and Pharmacoeconomics	Harvard Medical School


Appointments at Hospitals/Affiliated Institutions:
03/2022–06/2024	Research Fellow	Division of Pharmacoepidemiology and Pharmacoeconomics	Brigham and Women's Hospital

Other Professional Positions:
Year(s)	Position	Department	Institution
2008-2010	Health Policy Analyst	Health Department	Manitoba Keewatinowi Okimakanak
2012	Research Assistant	Department of Emergency Medicine	University of Manitoba
2012-2013	Statistical Analyst	First Nations Regional Longitudinal Health Survey	Assembly of Manitoba Chiefs
2013	Program Specialist	Aboriginal Health Programs	Winnipeg Regional Health Authority
2014-2015	Research Assistant	Centre for Aboriginal Health Research	University of Manitoba
2015	Research Consultant	Health Department	Manitoba Keewatinowi Okimakanak
2015-2017	Data Analyst	Manitoba Centre for Health Policy	University of Manitoba
2017-2021	Graduate Research Assistant	Tuberculosis Program	British Columbia Centre for Disease Control
2018	Teaching Assistant	School of Population and Public Health	University of British Columbia
2019	Graduate Research Assistant	Department of Pathology and Laboratory Medicine	University of British Columbia
2020-2021	Graduate Research Assistant	Canadian Disability Participation Project	University of British Columbia
2021-2022	Evidence Reviewer	McGill International TB Centre	McGill University
2022-	Statistical Consultant	Faculty of Health Sciences	Simon Fraser University


Committee Service:
Local
2022-2024	Lead, Pharmacoequity Team	Brigham and Women’s Hospital
2023-2024	Member, Department of Medicine’s Health Equity Innovation Pilot Program Learning Community.	Brigham and Women’s Hospital

National 
2015-2016	Judge, National Student Conference	Canadian Society for Epidemiology and Biostatistics

International
2018-2023	Member, TB and Mental Health Working Group	International Union Against TB and Lung Disease
2022-2024	Member, Abstract Committee	International Union Against TB and Lung Disease-North America Region
2021-2023	Chair, Global Indigenous Stop TB Initiative	International Union Against TB and Lung Disease
2023-2024	Member, Health Equity Special Interest Group	International Society for Pharmacoepidemiology
2022-2024	Member, Abstract Committee	International Union Against TB and Lung Disease-North America Region
2024	Abstract reviewer, 40th International Conference on Pharmacoepidemiology	tInternational Society for Pharmacoepidemiology

Professional Societies
2011-2012	Canadian Association of Health Services and Policy Research
2012-2016	Canadian Society for Epidemiology and Biostatistics
2012-	International Union Against Tuberculosis and Lung Disease
2023-	International Society of Pharmacoepidemiology

Editorial Activities:
    • Ad hoc Reviewer
American Journal of Public Health; BMJ Open; Canadian Journal of Public Health (x4); Clinical Infectious Disease; Cochrane; Critical Public Health; Global Public Health; Injury Epidemiology (x2); Injury Prevention; International Journal of Tuberculosis and Lung Disease (x2); Journal of General Internal Medicine (x2); Open Forum in Infectious Disease; PLoS One (x2); Postgraduate Medicine; Risk Management and Healthcare Policy; Tropical Medicine and International Health; Virology; Virulence.


Honors and Prizes:
2006	Student of Distinction	University of Winnipeg	Grade point average
2007	Academic Proficiency Scholarship	University of Winnipeg	Grade point average
2007	Academic Proficiency Scholarship	University of Winnipeg	Grade point average
2007	United College Class of ’50 Reunion Scholarship	University of Winnipeg	Competitive
2007	Manitoba Millennium Scholarship	Province of Manitoba	Grade point average
2007	Student of Highest Distinction	University of Winnipeg	Grade point average
2008	Student of Distinction	University of Winnipeg	Grade point average
2010	Health Services and Policy Research Studentship	Western Regional Training Centre	Competitive
2010	Network Environment for Aboriginal Health Research Fellowship.	Faculty of Medicine, University of Manitoba	Competitive
2011-2012	University of Manitoba Graduate Fellowship	Manitoba Health Research Council.	Competitive
2012	Summer Program in Data Analysis Travel Award	York University	Competitive
2012	National Student Conference Travel Award	Canadian Society of Epidemiology and Biostatistics	Competitive
2012	North America Region, 16th Annual Conference Travel Award	International Union Against Tuberculosis and Lung Disease	Competitive
2017-2018	Graduate Student Initiative Award	UBC Faculty of Medicine	Competitive
2021	Academic Excellence Initiative PhD Award	UBC President’s Office	Automatic
2022	Buffalo Blanket Ceremony	Communities Alliances and Networks	Board of Directors
2023	Research Staff Spotlight Award	Brigham Research Institute	Nomination
2024	Pillars of Excellence Award	Brigham and Women’s Hospital	Competitive


Report of Funded and Unfunded Projects
Current
10/2023-ongoing	“Foundations for Pharmacoequity: missing and misclassified race and ethnicity data in linked Mass General Brigham electronic health record (EHR) and Medicaid/Medicare claims data.”
Funding: Brigham and Women's Hospital Health Equity Innovation Pilot HEIP-2023/24 ($40,000).  Role: Research Lead.
Aims: (1) investigate structural missingness of race and ethnicity in EHR and claims data, comparing missing vs non-missing in terms of sociodemographics, health conditions, healthcare utilization; (2) evaluate concordance of race and ethnicity in claims data compared with EHR data taking into account missingness; (3) thoroughly document race and ethnicity variables available in Medicare and Medicaid benefits and enrolment files and Mass General Brigham (MGB) EHR.
10/2023-ongoing	“Multilevel drug utilization trend analysis: a reproducible R and SAS tutorial.”
Funding: None. Role: Principal Investigator.
Aims: (1) create a tutorial on multilevel and mixed effects modeling of aggregate count data that estimates trends for numerous aggregating units (e.g., states) that is reproducible with open source R code provided freely through a public GitHub repository; (2) develop a participatory workshop that can train, and (3) build an online learning community for mixed effect and multilevel modelling in pharmacoepidemiology.
01/2021-ongoing (unfunded)	“Survivorship Epidemiology”.
Funding: None.
Aims: The purpose of survivorship epidemiology is to share knowledge and advance theory and methods across fields of medicine (critical care, oncology, and infectious disease) in which survivorship is studied quantitatively; creating a critical mass of epidemiologists across fields dedicated to methodological research for survivorship.  I propose to mix causal inference quantitative theory and methods with the rich qualitative work done on survivorship within fields and to build bridges across fields to identify generalizable strategies, methods, and tools to address common problems such as comparator selection, decomposing the causal effects of critical illness in terms of physical illness effects, treatment effects, socioeconomic repercussions, and the psychological ramifications of surviving critical illnesses.


Report of Local Teaching and Training 
Local Invited presentations (last 3 years): 
  No presentations below were sponsored by 3rd parties/outside entities.
 07/2021	Towards survivorship epidemiology: a post-doctoral fellowship application / Oral
Division of Pharmacoepidemiology and Pharmacoeconomics, Brigham and Women's Hospital, Boston, MA
12/2022	Trends and characteristics of tramadol utilization in the United States, 2004-2021 / Oral
Division of Pharmacoepidemiology and Pharmacoeconomics, Brigham and Women's Hospital, Boston, MA
03/2023	Diseases as drugs: a target trial emulation framework for survivorship epidemiology? / Oral
Division of Pharmacoepidemiology and Pharmacoeconomics, Brigham and Women's Hospital, Boston, MA
05/2023	Multiple-Bias Sensitivity Analysis using Bounds / Journal Club
Division of Pharmacoepidemiology and Pharmacoeconomics, Brigham and Women's Hospital, Boston, MA
10/2023	Foundations for Pharmacoequity: Missing and misclassified race and ethnicity in linked electronic health records and Medicare and Medicaid claims data, 2000-2020 / Oral.
Division of Pharmacoepidemiology and Pharmacoeconomics, Brigham and Women's Hospital, Boston, MA
04/2024	Race and ethnicity in causal diagrams of health disparities
and in clinical prediction modelling: a journal club-style presentation of recent guidance from Howe et al. (2022) and Basu (2023)
Health Equity Innovation Pilot (HEIP) Program Learning Community, Dept of Medicine, Brigham and Women’s Hospital, Boston, MA.
05/2024	Missing and discordant race and ethnicity variable values in linked MGB EHR–CMS claims data, 2015-2019: a descriptive investigation.
Health Equity Innovation Pilot (HEIP) Program Learning Community, Dept of Medicine, Brigham and Women’s Hospital, Boston, MA.


Report of Regional, National and International Invited Teaching and presentations
Those presentations below sponsored by outside entities are so noted and the sponsor(s) is (are) identified.

Regional
03/2021
	“All together now: aggregating multiple records to develop a person-based dataset to integrate and enhance infectious disease surveillance in Ontario, Canada” / Oral. Canadian Public Health Association Journal Club, Online.

International
06/2011	Tuberculosis Incidence in Six Canadian Provinces, 1996-2009: Ethnic-origin specific rate ratios and trends.
Korean Institute of Tuberculosis, Osong, South Korea, June 22, 2011 (Oral).
03/2021	“An overview of systematic reviews with a focus on depression” / Invited Presentation.  In, World TB Day Webinar: Integrating TB and Mental Health Services to End the Epidemic. TB-Mental Health Working Group, International Union Against Tuberculosis and Lung Disease. https://youtu.be/eDH98iF-CBo?si=6Ly-mxjm9XxADTmc.
08/2023	Tramadol use in the United States, 2005-2021. / Selected Oral Abstract. 39th International Conference on Pharmacoepidemiology, Halifax, Canada. [grant funding from AHRQ supported travel, accommodations, and registration].


Report of Teaching and Education Innovations
Causing Careers: a causal inference approach to planning education and training exposures aimed at achieving long-term work and life goals as mediated by real-world experiences.	Causing careers has three objectives: (1) educating trainees in causal inference, (2) formalizing career planning through causal inference framework terminology, applying epidemiological concepts with methodological tools such as DAGs, PICOs, 2x2 tables, and basic probability theory while introducing counterfactual reasoning within the potential outcomes framework, and (3) contributing to the epidemiology’s scant pedagogical research.  A key implement for Causing Careers will be self-directed acyclic graphs (self-DAGs).  Self-DAGs create immediate relevance for learning DAGs by focusing on each individuals career goals (long-term and intermediate positions as outcomes).  By explicitly linking education and/or training exposures/interventions assumed to causative (necessarily or sufficiently) or at least contribute substantially) to realizing career outcomes.  Potential confounding factors (time-varying or baseline with fixed effects or interactions with education exposure or third variable(s), as assumed with rationale provided by the trainee).  These may affect both their education/training and career outcomes which can be discussed in terms of subject matter and in training students to understand differences between confounding, mediating, and other variables.  Trainees that can identify potential confounding on their career and education pathways may devise approaches to “adjust” away or otherwise block all backdoor paths between education exposure and career outcome).  Furthermore, baseline effect modification of the education/training can be included in text descriptions developed alongside the career causal graphs.  Using publicly available Daggity.net software (https://dagitty.net/) trainees will draw these career DAGs or self-DAGs that identify their specific, measurable, achievable, relevant, and timebound (SMART) career goals (outcomes) and will describe educational interventions (exposures) to cause this goal.  A starting exercise will be considering the Causing Career’s first goal of causal inference education, where we describe the concepts that define intended outcomes of the course.





Report of Education of Patients and Service to the Community
Those presentations below sponsored by outside entities are so noted and the sponsor(s) is (are) identified.
Activities
Years	Role	Organization	Sponsor
2004	Candidate, Member of Parliament (Canada)	Green Party of Canada	Green Party of Canada
2004-2006	Policy and Platform Development Committee	Green Party of Canada	Volunteer
2005-2006	Secretary	Green Party of Manitoba	Volunteer
2005-2006	Membership Development Coordinator	Green Party of Manitoba	Volunteer
2006-2007	Board Member	Manitoba EcoNetwork, Inc.	Volunteer
2007	Candidate, Member of the Legislative Assembly (Manitoba)	Green Party of Manitoba	Green Party of Manitoba
2006-2008	Leader	Green Party of Manitoba	Volunteer
2008	National Delegate	3rd Global Greens Congress	Green Party of Canada

Educational Material for Patients the Lay Community:
03/2023	TB or not TB?  What’s Happening in the Body.	One Vision, Many Paths: Indigenous Solutions for Tuberculosis and HIV.	Communities Alliances and Networks.

Recognition:
2004	U of W goes greener as it looks to the future	Winnipeg Free Press
2005	The SunSet project	Alma Mater Society of UBC
2006	U of W student to lead Green Party	Winnipeg Free Press
2007	Greens promise ban on cosmetic pesticides	Winnipeg Free Press
2022	Global Indigenous Stop TB Initiative: A TB Scientific Section Working Group	International Union Against TB And Lung Disease
2023	Team of Brigham Investigators Receive Department of Medicine Health Equity Innovation Pilot Award	Brigham and Women’s Hospital

Report of Scholarship 
(ORCiD: https://orcid.org/0000-0003-0506-7936) 
* denotes equal authorship contribution
** denotes mentored trainee.

Peer-Reviewed Scholarship in print or other media:

Research Investigations 	
    1. Basham CA, Snider C. Homicide mortality rates in Canada, 2000–2009: Youth at increased risk. Can J Public Heal. 2016;107(3):239. doi:10.17269/cjph.107.5391
    2. Basham CA, Elias B, Fanning A, Cook C, Orr P. Performance measurement of a Canadian provincial tuberculosis programme: Manitoba, 2008–2012. Int J Tuberc Lung Dis. 2018;22(4):437–443. doi:10.5588/ijtld.17.0508
    3. Romanowski K, Baumann B, Basham CA, Ahmad Khan F, Fox GJ, Johnston JC. Long–term all–cause mortality in people treated for tuberculosis: a systematic review and meta–analysis. Lancet Infect Dis. 2019;19:1129–1137. doi:10.1016/S1473–3099(19)30309–3
    4. Plourde PJ, Basham CA, Derksen S, et al. Latent tuberculosis treatment completion rates from prescription drug administrative data. Can J Public Heal. 2019;110(6):705–713. doi:10.17269/s41997–019–00240–1
    5. Basham CA, Elias B, Fanning A, Orr P. Tuberculosis among northern Manitoba First Nations, 2008–2012: program performance on– and off–reserve. Canadian Journal of Public Health 2019;110(6):688–696.
    6. Basham CA, Karim ME. Multimorbidity prevalence in Canada: a comparison of Northern Territories with Provinces, 2013/14. International Journal of Circumpolar Health. 2019;78(1):1607703.
    7. Basham CA, Smith S, Romanowski K, Johnston JC. Cardiovascular morbidity and mortality among people diagnosed with tuberculosis: a systematic review and meta-analysis. PLoS ONE 15(7):e0235821.
    8. Basham CA, Cook, VJ, Johnston JC. Towards a ‘fourth 90’: A population–based analysis of post–tuberculosis pulmonary function testing in British Columbia, Canada, 1985–2015. European Respiratory Journal. April 2020:2000384.
    9. Basham CA. Regional variation in multimorbidity prevalence in British Columbia, Canada: a cross–sectional analysis of Canadian Community Health Survey data, 2015/16. Health Promotion and Chronic Disease Prevention in Canada. 2020 Aug;40(7–8):225–234.
    10. Basham CA, Karim ME, Cook VJ, Patrick DM, Johnston JC. Post–tuberculosis mortality risk among immigrants to British Columbia, Canada, 1985–2015: a time–dependent Cox regression analysis of linked immigration, public health, and vital statistics data. Can J Public Heal. 2021;112(1):132–141.
    11. Basham CA, Karim ME, Cook, VJ, Patrick DM, Johnston JC. Post–tuberculosis airway disease among people immigrating to British Columbia, Canada, 1985–2015: a population–based cohort study. EClinicalMedicine. 2021;33:100752.
    12. Nikiforuk A, Kuchinski S, Twa DW, Lukac CD, Sbihi H, Basham CA, Steidl C, Prystajecky NA, Jassem A, Krajden M, Patrick DM, Sekirov I. The Contrasting Role of Nasopharyngeal Angiotensin Converting Enzyme 2 (ACE2) Transcription in SARS-CoV-2 Infection: A Cross-Sectional Study of People Tested for COVID-19 in British Columbia, Canada. EBioMedicine. 2021;66:103316.
    13. Basham CA, Karim ME, Cook, VJ, Patrick DM, Johnston JC. Tuberculosis–associated depression risk: a population–based cohort study of people immigrating to British Columbia, Canada, 1985–2015. Annals of Epidemiology. 2021; 63: 7-14.
    14. Basham CA, Karim ME. An E–value analysis of potential unmeasured or residual confounding in systematic reviews of post–TB mortality, respiratory disease, and cardiovascular disease. Annals of Epidemiology. 2022; 68: 24-31.
    15. Basham CA, Karim ME, Johnston JC. Multimorbidity prevalence and chronic disease patterns among tuberculosis survivors in a high-income setting. Can J Public Heal. 2023 Apr;114(2):264-276.
    16. Vadlamudi NK, Basham CA, Johnston JC, Ahmad Khan F, Battista Migliori G, Centis R, D'Ambrosio L, Jassat W, Davies MA, Schwartzman K, Campbell JR. The association of SARS-CoV-2 infection and tuberculosis disease with unfavorable treatment outcomes: A systematic review. PLOS Glob Public Health. 2023 Jul 19;3(7):e0002163.
    17. Martin Ginis KA, Sinden AR, Bonaccio S, Labbé D, Guertin C, Gellatly IR, Koch L, Mortenson BW, Routhier F, Basham CA, Jetha A, Miller WC. Experiential Aspects of Participation in Employment and Mobility for Adults With Physical Disabilities: Testing Cross-Sectional Models of Contextual Influences and Well-Being Outcomes. Archives of Physical Medicine and Rehabilitation. Published online August 20, 2023:S0003-9993(23)00462-8. doi:10.1016/j.apmr.2023.08.004
    18. Closson K, Zulu B, Jesson J, Dietrich JJ, Pakhomova T, Basham CA, Beksinska M, Kaida A. Examining gender and sexual orientation differences in physical intimate partner violence experienced and perpetrated by youth living in eThekwini district South Africa during the COVID-19 pandemic. BMC Public Health. 2023 Nov 21;23(1):2300.
    19. Zharima C. (co-first)*, Singh R. (co-first)*, Closson K., Beksinska M., Zulu B., Jesson J., Pakhomova T., Dong E., Dietrich J., Kaida A., Basham CA (senior). Economic hardship and perpetration of intimate partner violence by young men in South Africa during the COVID-19 pandemic (2021–2022): a cross-sectional study. Inj. Epidemiol. 2024. 11(2). https://doi.org/10.1186/s40621-024-00483-8.
    20. Jesson J, Zulu B, Closson K, Basham CA, Beksinska M, Dong E, Zharima C, Singh R, Pakhomova T, Dietrich J, Kaida A. Increased difficulty accessing food and income change during the COVID-19 pandemic among youth living in the eThekwini district, South Africa. Public Health Nutrition. Published online 2024:1-30. doi:10.1017/S1368980024001174.
    21. Basham CA, Edrees H, Huybrechts KF, Hwang CS, Bateman BT, Bykov K. Tramadol use in U.S. adults with commercial health insurance, 2005-2021. American Journal of Preventive Medicine. Published online June 12, 2024. doi:10.1016/j.amepre.2024.06.009
    22. Bea S, Huybrechts KF, Edrees HH, Basham CA, Vine SM, Glynn RJ, Bateman BT, Bykov K. Opioid overdose in patients with concomitant use of tramadol and clopidogrel versus alternative antiplatelet agents. J Am Coll Cardiol. 2024 (Accepted)


Other peer-reviewed scholarship
    1. Basham CA, Romanowski K, Johnston JC. Life after tuberculosis: planning for health. Lancet Respiratory Medicine. 2019;7(12):1004–1006.
    2. Basham CA, Grewal N, Orr PH, McMullin K, Wobeser WL. What will it take to achieve meaningful action on tuberculosis among Indigenous Peoples? International Journal of Tuberculosis and Lung Disease. 2020;24(5):661–664
    3. Basham CA. Post–tuberculosis outcomes science: a sub–discipline for TB survivorship research? International Journal of Tuberculosis and Lung Disease. 2021; 25(6):498-501.

Non-peer reviewed scholarship in print or other media:
Letters to the Editor
    1. Basham CA, Elias B, Orr P. Tuberculosis elimination in Canada. Lancet. 2019;394(10195):300–301. doi:10.1016/S0140–6736(19)31122–5
    2. Basham CA, Romanowski K, Johnston JC. Cardiovascular disease: the forgotten cousin of post-TB health? Int J Tuberc Lung Dis. 2020 Apr 1;24(4):466-467. doi: 10.5588/ijtld.19.0795. PMID: 32317076.
    3. Basham CA, Romanowski K, Johnston JC. Alcohol use disorder and TB survivor health: correspondence on Necho et al.’s systematic review. International Journal of Tuberculosis and Lung Disease. 2021;25(6):516-517.
    4. Basham CA, Orr PH. Monitoring TB program performance. Int J Tuberc Lung Dis. 2022 Jul 1;26(7):692-693.

Theses:
    1. Basham CA. Tuberculosis Prevention, Diagnosis, and Care: Manitoba, 2008-2010: A Performance Analysis. MSc Thesis: Department of Community Health Sciences, University of Manitoba. Approved: Jan. 2021.
    2. Basham CA. Tuberculosis Survivor Health. PhD Thesis: School of Population and Public Health, University of British Columbia. Approved: October 2021. Retrieved October 1, 2023 from: https://open.library.ubc.ca/collections/ubctheses/24/items/1.0402446.

Abstracts, Poster presentations, and Exhibits at Professional Meetings (past 3 years, not yet published as peer-reviewed articles):
    1. Basham CA, Edrees H, Vine S, Mastrorilli J, Oduol T, Bateman B, Glynn R, Huybrechts K, Bykov K. A cohort study of opioid overdose risk after oxycodone initiation during CYP3A4-inhibiting vs non-inhibiting calcium channel blocker therapy: United States, 2000-2020. The 39th International Conference on Pharmacoepidemiology. August 23-27, 2023. Halifax, Canada. [poster]
    2. Bykov K, Basham CA, Khan N, Vine S, Edrees H, Mastrorilli J, Bateman B, Glynn R, Huybrechts K. Risk of Opioid Overdose with Concomitant Use of Oxycodone and Selective Serotonin Reuptake Inhibitors. The 39th International Conference on Pharmacoepidemiology. August 23-27, 2023. Halifax, Canada. [selected oral abstract presentation by KB].
    3. Oduol T, Basham CA. Missing Race and Ethnicity Data in Medicaid: A Multilevel Analysis of Trends by State (2016-2022). The International Society for Pharmacoepidemiology Mid-Year Meeting. https://www.pharmacoepi.org/meetings/2024mym/agenda/oral-presentations-and-posters/ April 14-16, 2024. Miami, Florida. [selected oral abstract presentation by TO]
    4. Basham CA, Oduol T, Weberpals J, Hwang C, Rome B.  Race and Ethnicity Variables in Real-World Data: Implications for Reproducibility in Pharmacoepidemiology. The 40th International Conference on Pharmacoepidemiology (ICPE). August 24-28, 2024. Berlin, Germany. [poster]
    5. Basham CA, Hyubrechts K, Batemen, B, Vine S, Edrees H, Glynn R, Bykov, K.   Co-Administration of Oxycodone and CYP3A4-Inhibiting Calcium Channel Blockers and Opioid Overdose: Real-World Evidence from Population-based Claims Data in the United States, 2000-2020. The 40th International Conference on Pharmacoepidemiology (ICPE). August 24-28, 2024. Berlin, Germany. [poster]

Reports:
    1. MKO Health. Policy Analysis and Position Paper on Non-alcohol-based hand sanitizer for Northern Manitoba First Nations during the H1N1 Pandemic. Manitoba Keewatinowi Okimakanak, Inc. Thompson, Manitoba. (ed to Health Canada – First Nations and Inuit Health Branch). 2009.
    2. MKO Health. Statistical Analysis of Northern Manitoba First Nations Housing. Manitoba Keewatinowi Okimakanak, Inc. Thompson, Manitoba. 2009.
    3. MKO Health. Briefing Note on Methicillin Resistant Staphylococcus Aureus (MRSA) in Northern Manitoba First Nations. Manitoba Keewatinowi Okimakanak, Inc. Winnipeg, Manitoba. (ed to Manitoba Health and Health Canada First Nations and Inuit Health Branch). 2009. [Description: analysis of monthly communicable disease reports and literature review to find potential solutions].
    4. MKO Health.  Policy Analysis of Differential Response to H1N1 in Northern Manitoba First Nations compared to Northern Ontario First Nations. Manitoba Keewatinowi Okimakanak, Inc. Winnipeg, Manitoba. (Used for internal planning regarding and best practices for community leadership and political advocacy regarding oseltamivir and zanamivir). 2010.
    5. Assembly of Manitoba Chiefs (AMC), First Nations Regional Health Survey (RHS) Phase 2 (2008- 2010): Manitoba Regional Report. Winnipeg: Assembly of Manitoba Chiefs, June 2012 (Revised November 2012). https://web.archive.org/web/20170612153018/http://www.fnhssm.com/images/PDF/rhs-survey-2008-10-regional-report.pdf.
    6. Lix LM, Plourde PJ, Larcombe L, Kinew KA, Basham CA, Derksen S, Srisakuldee W, Schultz J, and McCulloch S. Exploring Tuberculosis Treatment, Management, and Prevention in Manitoba’s Administrative Health Data. Winnipeg, MB. Manitoba Centre for Health Policy. Autumn 2018. http://mchp-appserv.cpe.umanitoba.ca/reference/MBTB_Report_web.pdf
    7. Katz A, Kinew KA, Star L, Taylor C, Koseva I, Lavoie J, Burchill C, Urquia ML, Basham CA, Rajotte L, Ramayanam V, Jarmasz J, Burchill S. The Health Status of and Access to Healthcare by Registered First Nation Peoples in Manitoba. Winnipeg, MB. Manitoba Centre for Health Policy. Fall 2019. https://mchp-appserv.cpe.umanitoba.ca/reference/FN_Report_web.pdf


>>>>>>> 6352eb196761aa32d6f909d3400d2c0763c335a0
